"""empty message

Revision ID: c77121166349
Revises: 
Create Date: 2018-11-21 16:18:57.929978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77121166349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_genre'), 'game', ['genre'], unique=True)
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_index(op.f('ix_game_genre'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
